MOD: F.A.Q. Administration v1.1 - Add Default FAQs
[INSERT]
FAQ_CATEGORY
(FCAT_TITLE,FCAT_ORDER,FCAT_LEVEL)#('General',1,4)
[END]
[INSERT]
FAQ
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Do I have to register?','',1,1,1)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('How can I use smilies and images?','',1,1,2)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I add a hyperlink to my messages?','',1,1,3)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I change the format of my text?','',1,1,4)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('What are Moderators?','',1,1,5)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Are cookies used?','',1,1,6)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('What are active topics?','',1,1,7)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I edit my own posts?','',1,1,8)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I attach files?','',1,1,9)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I search?','',1,1,10)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I edit my profile?','',1,1,11)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I attach my own signature to my posts?','',1,1,12)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Are there any censor features?','',1,1,13)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('What do I do if I forget my Password?','',1,1,14)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Can I be notified by e-mail when there are new posts?','',1,1,15)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('What does it mean if a forum has Moderation enabled?','',1,1,16)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('What is COPPA?','',1,1,17)
(F_FAQ_QUESTION,F_FAQ_ANSWER,F_FAQ_ORDER,F_FAQ_CATEGORY,F_FAQ_TYPE)#('Where can I get my own copy of this Forum?','',1,1,18)
[END]