MOD: F.A.Q. Administration v1.1
[CREATE]
FAQ
F_ID
F_FAQ_QUESTION#VARCHAR (100)#NULL#
F_FAQ_ANSWER#memo#NULL#
F_FAQ_ORDER#int#NULL#1#
F_FAQ_CATEGORY#int#NULL#1#
F_FAQ_TYPE#int#NULL#0#
[END]
[CREATE]
FAQ_CATEGORY
FCAT_ID
FCAT_TITLE#varchar(100)#NULL#
FCAT_ORDER#int#NULL#1#
FCAT_LEVEL#int#NULL#
[END]