UserGroups MOD v1.0 b3
[CREATE]
USERGROUPS
USERGROUP_ID
USERGROUP_NAME#varchar(100)##
USERGROUP_DESC#memo#NULL#
USERGROUP_TYPE#int##0
AUTOJOIN#int##0
MEM_HIDE#int##0
MOD_HIDE#int##0
[END]

[CREATE]
USERGROUP_USERS

USERGROUP_ID#int##
MEMBER_ID#int##
MEMBER_TYPE#int##1
[END]

[CREATE]
ALLOWED_USERGROUPS

USERGROUP_ID#int##
FORUM_ID#int##
PERMS#int##0
[END]

[INSERT]
CONFIG_NEW
(C_VARIABLE,C_VALUE)#('STRUGVIEW','0')
(C_VARIABLE,C_VALUE)#('STRUGMEMVIEW','0')
(C_VARIABLE,C_VALUE)#('STRUGMODFORUMS','0')
[END]